### ISSUE TITLE
SyntaxError: 'return' outside of function (114:2)

### ISSUE THREAD

**Issue by Minwe** [substack/bundle-collapser#13]
I using `bundle-collapser` as browserify plugin, it throws a error:

https://travis-ci.org/allmobilize/amazeui/builds/66148876

```
/home/travis/build/allmobilize/amazeui/node_modules/bundle-collapser/node_modules/falafel/node_modules/acorn/dist/acorn.js:1747
  throw err;
        ^
SyntaxError: 'return' outside of function (114:2)
    at Parser.pp.raise (/home/travis/build/allmobilize/amazeui/node_modules/bundle-collapser/node_modules/falafel/node_modules/acorn/dist/acorn.js:1745:13)
    at Parser.pp.parseReturnStatement (/home/travis/build/allmobilize/amazeui/node_modules/bundle-collapser/node_modules/falafel/node_modules/acorn/dist/acorn.js:2552:74)
    at Parser.pp.parseStatement (/home/travis/build/allmobilize/amazeui/node_modules/bundle-collapser/node_modules/falafel/node_modules/acorn/dist/acorn.js:2427:19)
    at Parser.pp.parseBlock (/home/travis/build/allmobilize/amazeui/node_modules/bundle-collapser/node_modules/falafel/node_modules/acorn/dist/acorn.js:2692:21)
    at Parser.pp.parseStatement (/home/travis/build/allmobilize/amazeui/node_modules/bundle-collapser/node_modules/falafel/node_modules/acorn/dist/acorn.js:2443:19)
    at Parser.pp.parseIfStatement (/home/travis/build/allmobilize/amazeui/node_modules/bundle-collapser/node_modules/falafel/node_modules/acorn/dist/acorn.js:2546:26)
    at Parser.pp.parseStatement (/home/travis/build/allmobilize/amazeui/node_modules/bundle-collapser/node_modules/falafel/node_modules/acorn/dist/acorn.js:2425:19)
    at Parser.pp.parseTopLevel (/home/travis/build/allmobilize/amazeui/node_modules/bundle-collapser/node_modules/falafel/node_modules/acorn/dist/acorn.js:2379:21)
    at parse (/home/travis/build/allmobilize/amazeui/node_modules/bundle-collapser/node_modules/falafel/node_modules/acorn/dist/acorn.js:101:12)
    at module.exports (/home/travis/build/allmobilize/amazeui/node_modules/bundle-collapser/node_modules/falafel/index.js:31:15)
```

Browserfiy configs like this:

https://github.com/allmobilize/amazeui/blob/3e766a008b8e746a73a6851b975a428d63869f42/gulpfile.js#L207-L244

## How to reproduce

1. clone https://github.com/allmobilize/amazeui/tree/3e766a008b8e746a73a6851b975a428d63869f42
2. `npm install && gulp build:js:browserify`

**Comment by chrisjhoughton** [comment]
+1

**Comment by Minwe** [comment]
It seems caused by my code https://github.com/allmobilize/amazeui/blob/532723d84f06d5b5b863074fa174ee3b23e7c393/js/util.fullscreen.js#L114

I deleted this line then it works.
