### ISSUE TITLE
Cannot call method 'forEach' of undefined

### ISSUE THREAD

**Issue by huang47** [substack/bundle-collapser#6]
While using bundle-collapser with our internal project I found below problems

after upgrading browser-unpack dependency to 1.0.0 which solves the problem

```shell
TypeError: Cannot call method 'forEach' of undefined
    at module.exports (/Users/hhuang/netflix/users/hhuang/kubrick/build-kubrick/node_modules/bundle-collapser/index.js:8:10)
    at Object.<anonymous> (/Users/hhuang/netflix/users/hhuang/kubrick/build-kubrick/t.js:6:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

**Comment by ForbesLindesay** [comment]
This should be closed now.
